-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-yaml
    -   id: check-xml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: flake8
        args: ["--exclude=docs/conf.py"]

-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: 1.0.4
    hooks:
    -   id: python-import-sorter
    args: ['--check-only', '--diff']

-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        files: ^(xobject|tests).*\.py$

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: py.test
        language: system
        files: ^(xobject|tests).*\.py$
        args:
        - --cov=xobject
        - --cov-report=term-missing
        - --verbose
        - --pep257
        - tests/
